# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'
use_frameworks!

target 'AcceptSDK' do
  #React
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'CxxBridge',
  'DevSupport',
  'RCTNetwork',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTWebSocket', # needed for debugging
  # Add any other subspecs you want to use in your project
  ]
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'AuthorizeNetAccept'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  target 'AcceptSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end

